FROM ruby:2.6.3
LABEL maintainer="benedict@benedict.com"

# Allow apt to work with https-based sources
RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends \
    apt-transport-https

# Ensure we install an up-to-date version of Node
# See https://github.com/yarnpkg/yarn/issues/2888
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

# Ensure latest packages for Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | \
    tee /etc/apt/sources.list.d/yarn.list

# Install packages
RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends \
    nodejs \
    yarn \
    nano

RUN mkdir /app
COPY Gemfile* /app/
WORKDIR /app
RUN bundle install
COPY . /app

RUN chmod +x ./entrypoint_prod.sh
ENTRYPOINT [ "./entrypoint_prod.sh" ]
RUN bundle exec rake RAILS_ENV=production assets:precompile
VOLUME ["RAILS_ROOT/public"]
ENTRYPOINT [ "./docker-entrypoint.sh" ]
CMD ["bin/rails", "s", "-b", "0.0.0.0"]